#!/usr/bin/env ruby

# TODO: Get host IP from the interlock container specifically (`docker port interlock`)

require "thor"

class Carina < Thor

  desc "bootstrap", "Build everything (idempotent)"
  def bootstrap
    puts "Bootstrapping cluster (idempotently)"
    system "source carina/build; build_all"
    invoke :info
  end

  desc "info", "Show the IP and port(s) your application is available"
  def info
    puts "\n\nNow available on:"
    puts `docker port interlock`
  end

  desc "db_setup", "Rebuild, load, migrate and seed the database"
  def db_setup
    puts "Setting up DB"
    system "source carina/build; build_db_setup"
  end

  desc "latest", "Deploy the latest Rails code"
  def latest
    invoke :build_image
    puts "Deploying image containers"
    system "source carina/build; build_deploy"
    invoke :info
  end

  desc "elasticsearch", "Rebuild the ElasticSearch container"
  def elasticsearch
    puts "Building Elasticsearch container"
    system "source carina/build; build_elasticsearch"
  end

  desc "image", "Rebuild the Rails image with current code"
  def build_image
    puts "Building the Rails image"
    system "source carina/build; build_image"
  end

  desc "interlock", "Rebuild the Interlock container"
  def interlock
    puts "Building Interlock container"
    system "source carina/build; build_interlock"
  end

  desc "kibana", "Rebuild the Kibana container"
  def kibana
    puts "Building Kibana container"
    system "source carina/build; build_kibana"
  end

  desc "logstash", "Rebuild the Logstash container"
  def logstash
    puts "Building Logstash container"
    system "source carina/build; build_logstash"
  end

  desc "postgres", "Rebuild the Postgresql container"
  def postgres
    puts "Building Postgresql container"
    system "source carina/build; build_postgres"
  end

end

Carina.start
